### ISSUE TITLE
测试出一些bug，希望能改进

### ISSUE THREAD

**Issue by SupZ6** [sleep1223/fast-soy-admin#11]
- [ ] 用户管理>新增>确认：500错误
- [ ] 角色管理>编辑(管理员)>菜单权限(随便勾选)>确认：404错误，但新增加的角色又能编辑成功
- [ ] 角色管理>编辑(随便选一条)>按钮权限：404错误
- [ ] 角色管理>编辑(随便选一条)>按钮权限(随便勾选)>确认：404错误
- [ ] 登录(管理员或普通用户)>确认：404错误，提示无法登录，刷新页面后一直loading，要删除浏览器本地存储的SOY_token键才能到登录界面，用超级管理员账户登录正常

**Comment by SupZ6** [comment]
换成PostgreSQL就没出现这些问题了，我在继续折腾一下…

**Comment by sleep1223** [comment]
原来用的是Mysql数据库吗?

**Comment by SupZ6** [comment]
之前用的是默认数据库SQLite

**Comment by saylaughs** [comment]
为什么点击注册账号，没反应？

**Comment by SupZ6** [comment]
> 为什么点击注册账号，没反应？

没做注册接口，肯定没反应啊

**Comment by saylaughs** [comment]
> > 为什么点击注册账号，没反应？
> 
> 没做注册接口，肯定没反应啊

不是 我说的登录页面 连跳转都跳转不了 能帮忙看看吗

**Comment by SupZ6** [comment]
怎么帮你看？

**Comment by saylaughs** [comment]
😂加个wx 有空一起交流技术

**Comment by SupZ6** [comment]
> 😂加个wx 有空一起交流技术

行，我加你

**Comment by saylaughs** [comment]
好👌 saylaugh
这是我的wx 麻烦了
