### ISSUE TITLE
tortoise cant find

### ISSUE THREAD

**Issue by Cohawv** [sleep1223/fast-soy-admin#2]
ImportError: cannot import name 'fields' from 'tortoise' (/usr/local/lib/python3.12/dist-packages/tortoise/__init__.py)

**Comment by sleep1223** [comment]
It seems to be an environmental issue. Please use the recommended deployment methods.
Try deploying the project using `pdm` or `Docker`.
[https://github.com/sleep1223/fast-soy-admin/blob/master/README.en.md#Usage](https://github.com/sleep1223/fast-soy-admin/blob/master/README.en.md#Usage)
