### ISSUE TITLE
请教大佬一个问题，apis权限和菜单、按钮权限功能是否有重叠

### ISSUE THREAD

**Issue by obrua** [sleep1223/fast-soy-admin#3]
请教大佬一个问题，apis权限和菜单、按钮权限功能是否有重叠
按现在常用系统的逻辑，是配置菜单和按钮权限即可控制权限部分，我看现在多了个apis权限，会不会有点重复配置过于繁琐。

大佬可以解释下他的作用和用法么？
感谢

**Comment by sleep1223** [comment]
apis权限是用来防止越权和攻击, 我从后端的角度上觉得它是有必要的. 

请求会先经过 验证token -> 验证权限 -> 业务逻辑
